server:
  port: 8002
spring:
  application:
    name: provider-ticket
eureka:
  instance:
    prefer-ip-address: true  # 注册服务的时候使用服务的ip地址
  client:
    register-with-eureka: true  #把自己注册到eureka上
    fetch-registry: true  #从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
